# Generated by Django 4.2.7 on 2023-11-08 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleNMR', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('preparation_Status', models.CharField(max_length=1)),
                ('balance', models.IntegerField(default=0)),
                ('average_usage_per3year', models.IntegerField(default=0)),
                ('average_usage_per5year', models.IntegerField(default=0)),
                ('num_of_devices_use_item', models.IntegerField(default=0)),
                ('suggested_assessment', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('assessment', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('assess_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('responsible', models.CharField(max_length=255)),
                ('duedate', models.DateTimeField()),
                ('registerdate', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='equipment.component')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.CharField(max_length=10, unique=True)),
                ('risk_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('condition_EL_assess', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('condition_MEC_assess', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('components_EL_assess', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('components_MEC_assess', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('assessment', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='parent')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='equipment.equipment'),
        ),
    ]
