# Generated by Django 4.2.7 on 2023-11-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='parent',
        ),
        migrations.AddField(
            model_name='equipment',
            name='component',
            field=models.ManyToManyField(blank=True, related_name='components', to='equipment.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, default=''),
        ),
    ]
