# Generated by Django 4.2.7 on 2023-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_parent_equipment_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='components', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='component',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='equipment.component'),
        ),
    ]
